# Generated by Django 5.0 on 2024-02-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccount_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='gender',
        ),
    ]
